apiVersion: v1
name: mop
description: A Helm chart for Kubernetes for the MOP TOM

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. Don't change it. The helmPipeline() appends the git hash to it as needed.
version: 0.2.0

# This is the version number of the application being deployed. Don't change it. This value
# is edited by helmPipeline() to be consistent with the latest git-tag on the master branch of the repository.
appVersion: 0.0.0
